kind: ENC[AES256_GCM,data:bHJeXwbP,iv:IYRoDZqHz62Sxsk7/m1Kyseo/sn55jc93NRk8pvSBfQ=,tag:8qkZCRVs06Xqh0MzNXsZhg==,type:str]
ansible_user: ENC[AES256_GCM,data:rpCE2tg2,iv:tkeMDren4fZU7gIIhVZqptXg+UwU4tYXE1fVq6SU+MA=,tag:0fBKpav8U5bGSp78tcXuAw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:agd8eePUwb/8eA1f7xg9Iw6KOBKo73/88Q==,iv:GBKE2RfLwRCoHQKg0UKQPaLzpaiYZPaYHzkrm4H9S/E=,tag:CZ/bxaf5gJTVdI9sn7OvKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVelQxT0N5K2lsTnlLTFM3
            bnFabnBuQkdWSE1EdkIxNmZTRzFWTFhGT0V3CmxGcHo5Y2dMWld5aXgyOTZzdjVQ
            aEQzanpDUXh6QWMzUmF3M3M1eWtQRVUKLS0tIFBNUnJ0Zm9lMW0xWkdEbFViUVdq
            Vnl0WWtKVW55RjRhVmdydkM1Ky9FQTAKtR7U0xMZNssptowCLKR9JEYMmI0Pg8SL
            nXlzHP5FF/+lszUWuC23c8fjXU55Y3ZuJZssygBEw+wnzFnGhog39Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T13:52:11Z"
    mac: ENC[AES256_GCM,data:ryxST+U5Kat77a0v0dro2PNm4i0J4SHqh6O9TzU97+YuHerK1EwMYFbyfaFHBwMC1e5Nd9RcqaXVbTCItEdlwaXn+WG8KnL0rKOblJiEqy5RiDTwqaLssxJBtnmtwVwyQmTeTVKsgeB0Zv1Dhuh62MJe2ppQSeXS1e8lerwpbzk=,iv:37RzASE9NpSkdJndEDpeuunnrlrJ0M2Emp7WgtkeVMA=,tag:49BOY+/7VMQl/5kQdunDDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
