kind: ENC[AES256_GCM,data:VySVRj/v,iv:MmJdq2yNxG6lKOArTcETOs+k8JtzYXlbdR4dRwa6+ig=,tag:N4w/ZpsfYRfdGcWQQmfENw==,type:str]
ansible_user: ENC[AES256_GCM,data:Nbu26RpS,iv:3ooIrnSb4qwQKTm/VyKUj57+GdQJ4mpnRvBl01kmARw=,tag:Aaic78D12XQ0X98+J0Wipw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BocfkD9jgJBw6R1Jgm7w+/ouzQXaqlnUGA==,iv:QHUs+Wmha6RPcfh3WnrYZEGbeeedxywLLX2I4Mvd8rE=,tag:MroNgCB13J4fbX2cXX/52Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UlI3SEVqbmNiRjBZS0hl
            dzh1NDBPUkhiU2xscmpQeWJEUXdGcUlMY2o0CndFWElJUm1BcGlKQ2JrTXNsbUl5
            MGhiRkFqRlpxQ3BzQUZnSW13dVlieUUKLS0tIE5Vb1Y1Ri9XOUxSSVo4b3l5RlZG
            ZFJsbFQrQzB6VkpvOTd5bzlHUmJFOUEKYsyd8m2+y4w2wQM+WIBmwGQfC3raLiRT
            M+B4dpyQzLfKMEVmJOi9UdRTM8QGJJQGZdRYN9FvLA5FdcdPqWQD5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-13T01:34:33Z"
    mac: ENC[AES256_GCM,data:x4MxEjSFPS0O8ftrPk5mVu/4aHCPgInvqCbEIJtwDfwXocNTti4XJvMyIY9oaUSmLBi+iaawiAuZ9gXf8F3Evctuy5HCx/p4P9/EtyuLmOGyplaM7ur3YjjLPvv1Ds3d+J83n/+ZAD8a83XAdRKGj9VA9Sm0BQ0gRAQHp8We8IE=,iv:n7SnyeWzz2qmbjyUcgjcM6Z76DBe9xOWsgyie7P+kl4=,tag:qBdOHrOpmetVNURksulgVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
