apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:mReNdI10yUcGa980ZQrTGWyKdEGocxgJ,iv:4D0MZUcqIZrfYhohX28/+vvFUb3VZn+GEmv90zj+G30=,tag:c/u3E9Z8nKQx0+OKwMS9ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa1A3RTlDQVh1MmVta0kw
            V0ZuSVp1V3pqU2QrY1ZUOVhPd1lNSDZ4WW1JCm1RbjdmV3M5d0gzLzdCV1d5c0ZB
            dld5L1lCVHhYOTBRSTJ3MEZ2UFJRUlUKLS0tIFUzNHpXUjlsVTg1c3JWN0lmeEdX
            QWR5RVdGS1V6MmkyR0JuVGpKdUpUNWsK0D4BcZves3oMPFhOVQFP50w2wo+6ecNj
            ikBYBJBpPs9U9w5IjavRMgWDzI7g/e1rdYT4LQFZhM6fnNdWb6b9+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T13:52:11Z"
    mac: ENC[AES256_GCM,data:w8oFHB2I5VPK/zQL+6X61ExQqk6HotOkJH04Mn+YkQm+gcKl4xFiBXhNzRP/9c+aXiYF8vE/5pHfut2FYaAXCs3TXCVO+mPN5xsaz4/Fo9q8+7t6y4PMyObd7eBUuy/+ndqAXY7pzhUkBLAlGwYVCE57nlnCD0bEmz4x2T2to5M=,iv:fMxcl1jA18fCv8OJLLLXbM/MAsRBJv1cwYhdXyBAnro=,tag:It1w5HW3979s4MDkqgn6NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
