---
kubernetes:
  children:
    master:
      hosts:
        qnti-01:
          ansible_host: 192.168.11.101
        qnti-03:
          ansible_host: 192.168.11.103
        qnti-07:
          ansible_host: 192.168.11.107
    worker:
      hosts:
        qnti-00:
          ansible_host: 192.168.11.100
        qnti-02:
          ansible_host: 192.168.11.102
        qnti-04:
          ansible_host: 192.168.11.104
        qnti-05:
          ansible_host: 192.168.11.105
        qnti-06:
          ansible_host: 192.168.11.106
        qnti-08:
          ansible_host: 192.168.11.108
