apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:qzdyE1ISSCU5n3OfT6oxMLOCe4oPBoVRXE4=,iv:i50xEQsq2p130n5WdrOdr5V0fGa488FxSK24TilCTMU=,tag:PFET7APBqeRqPrpEkRX1gg==,type:str]
    api-key: ENC[AES256_GCM,data:hLpBIghguZFpr1NzSBz8wabibVIE22ZEwsA6e4LqVJpehFxjeg==,iv:B9Y/m2TEoXtvROMBK4Axjp5iNKJoSHsuzeVxWLWBTys=,tag:gpgTBypy3A4f7PqqfdyE9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRDlyV1k4eUhwNCt6ejdD
            ODYxSlRGdTlSb3FiSk1TM09tem9DWlV5NURRCm0za0NtWUo5OVNNTVlrcXlmdEp0
            ZGxUQzdONHZwNDI5UHpFOXpxRExLWUEKLS0tIEdWT0FnVVBMc1FjK3ZrM3NGTE03
            ME5WQnp0QksvUzFiZDBmTzJ5QWlvbVkKiAxC9Pnk0R8zWOjXwIQlVk7e58zcv09w
            AbQuEsQdJA+6w6izonOiAxiqkS82iw+M4MplDnLuhRyE9jzRHln1+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T13:52:11Z"
    mac: ENC[AES256_GCM,data:Z2yYjmlHQI+tKsNbpRxHJo+lWZUTZ6W1jI/BFExQnPX42itoVtdEKpbAnDyVt65A0mAQKpnIHJXcneprnAFp0CJIPgv2YHHIKA1vCYUBiAOnweOCDDZYhexogZYkUhyZDv0HEvvXMeY8zlQu49spwP4LI2Lg+1/ckFxAvCaZE8g=,iv:SbCSzwHM8gTScfhjl6fbCYRQkTkoMo1T6iQLXzO1rCo=,tag:fRJ/6YsSeXXvea85wTIKTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
