---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  METALLB_LB_RANGE: "192.168.11.244-192.168.11.250"
  METALLB_K8S_GATEWAY_ADDR: "192.168.11.250"
  METALLB_INGRESS_ADDR: "192.168.11.249"
  KUBE_VIP_ADDR: "192.168.11.254"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
