apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Glhq2rVyq042bgsNGE5ZClOWu9VmJz1TQ6U+SDkE+7aCIkcu,iv:ZWSP6hB7H9d5KcJ3qs7U0zLp5vfzoIiFmZOvVp3l1HU=,tag:jrIAmycb+PdU+qqAwfqT+Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:dVdnQxL3pxTeRql8U912Dbx/3jbksvh9ncP9n6594M0O2wHtgmDCPiO528gdXoKgDlLcpveT5n5dGZ19U5z8PeO+xzBKXpsl3Hzly8lvFH5EwtxnJR2lnKk+PvTpRprT/U/2te5iNoBufqWFegLfJ2xkl0YDG0p6mvnt+hJy8GuutP+nxolFYY1g0ULegqkgOTGlUrIvCuG2KeWwg0w5vDucaGiEmQy/tVOmDiQexw==,iv:BBajA4aAdHTh3D4WsLn3lGjhOv2vgYwNTaBIMyDyHNk=,tag:rfmp8RXcOi9/8trMkQN62w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tyfpnkcp0wvlkfz2j3tdhcw4aghvwp36qepdndjkmhmy9h3ygczswkxtf4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM0RieE9LRXIyTzBKV2M4
            a0JuRDFyeXovMVVva1hFeExNVThKbWp1ckRnCjVSQ2JLQ0M2V05jN1A4aDRJSHQw
            bEMrZTFtMk50T1FMN1p4b0tET0hFd1kKLS0tIGVyalF0T2VGcjQ1S3dKMjVLWUJW
            Rk9Lb21vOEFoeVd3T2pXZVUxY1lGaDgK5litMQrwwEkZmYY9pILFte5V9dcVE+MI
            5Px+8Ep3Rnr9k/HzimfpxU6Cd94EbIUT92AVNvr1iAoG4hhUHVly4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T13:52:11Z"
    mac: ENC[AES256_GCM,data:sNOOSH6iVjMBPLtzqcUcZGyLYT8Op9D7m0tE+YdzqMUTTk7mHZpw9qCBeysK2kmGKW1I3FLEDDuKBGTznNZ2r1lvDiqU2EnWbgq0DS1mqYFcWhWK0MKPrDrfwCPMEIDqgvq7Al32Hphp39Jy1k2QrqJ95UAW6hFa5sUOoy/2Fdg=,iv:QkifYQ3uZPPePeeiKqGmmZJSO6qE2TSXuHfVEpSVTXI=,tag:qr9zPl7DBDrCgZbmtDr99g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
